### ISSUE TITLE
What is the meaning of 'using domain name'?

### ISSUE THREAD

**Issue by eliumoraes** [thangchung/clean-code-dotnet#114]
English is my second language and sometimes I dont really get the meaning of some phrases.
I'm trying to understand the part that says to always use domain name in the 'Naming' section.

**Comment by allamkuladeep** [comment]
@eliumoraes  - In One Solution we can have multiple projects that are basically represented with Unique name(Domain Name).
Under these projects we can have numerus classes defined. In order to categorize we create them we add Domain Name as suffix to the file/class/controller name. Which helps us to understand the purpose.

**Comment by eliumoraes** [comment]
Thank you @allamkuladeep I got it now!
